version: '2'
services:
    web:
        build:
            context: .
            args:
                workdir: /testapp
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - .:/testapp
            - ~/.ssh:/root/.ssh
        ports:
            - "3000:3000"
        volumes_from:
            - bundle
    bundle:
        image: testapp_web
        volumes:
            - /bundle
